export type StateOption = {
	label: string;
	value: string;
};

export type CityOption = {
	label: string;
	value: string;
	city: string;
	state: string;
};

const slugify = (text: string) =>
	text
		.toUpperCase()
		.replace(/[^A-Z0-9]+/g, "_")
		.replace(/^_+|_+$/g, "");

export const STATES: StateOption[] = [
	{ label: "Andhra Pradesh", value: "ANDHRA_PRADESH" },
	{ label: "Arunachal Pradesh", value: "ARUNACHAL_PRADESH" },
	{ label: "Assam", value: "ASSAM" },
	{ label: "Bihar", value: "BIHAR" },
	{ label: "Chhattisgarh", value: "CHHATTISGARH" },
	{ label: "Goa", value: "GOA" },
	{ label: "Gujarat", value: "GUJARAT" },
	{ label: "Haryana", value: "HARYANA" },
	{ label: "Himachal Pradesh", value: "HIMACHAL_PRADESH" },
	{ label: "Jharkhand", value: "JHARKHAND" },
	{ label: "Karnataka", value: "KARNATAKA" },
	{ label: "Kerala", value: "KERALA" },
	{ label: "Madhya Pradesh", value: "MADHYA_PRADESH" },
	{ label: "Maharashtra", value: "MAHARASHTRA" },
	{ label: "Manipur", value: "MANIPUR" },
	{ label: "Meghalaya", value: "MEGHALAYA" },
	{ label: "Mizoram", value: "MIZORAM" },
	{ label: "Nagaland", value: "NAGALAND" },
	{ label: "Odisha", value: "ODISHA" },
	{ label: "Punjab", value: "PUNJAB" },
	{ label: "Rajasthan", value: "RAJASTHAN" },
	{ label: "Sikkim", value: "SIKKIM" },
	{ label: "Tamil Nadu", value: "TAMIL_NADU" },
	{ label: "Telangana", value: "TELANGANA" },
	{ label: "Tripura", value: "TRIPURA" },
	{ label: "Uttar Pradesh", value: "UTTAR_PRADESH" },
	{ label: "Uttarakhand", value: "UTTARAKHAND" },
	{ label: "West Bengal", value: "WEST_BENGAL" },
	{
		label: "Andaman and Nicobar Islands",
		value: "ANDAMAN_AND_NICOBAR_ISLANDS",
	},
	{ label: "Chandigarh", value: "CHANDIGARH" },
	{
		label: "Dadra and Nagar Haveli and Daman and Diu",
		value: "DADRA_AND_NAGAR_HAVELI_AND_DAMAN_AND_DIU",
	},
	{ label: "Delhi", value: "DELHI" },
	{ label: "Jammu and Kashmir", value: "JAMMU_AND_KASHMIR" },
	{ label: "Ladakh", value: "LADAKH" },
	{ label: "Lakshadweep", value: "LAKSHADWEEP" },
	{ label: "Puducherry", value: "PUDUCHERRY" },
];

export const STATE_CITY_MAP: Record<string, string[]> = {
	ANDHRA_PRADESH: [
		"Visakhapatnam",
		"Vijayawada",
		"Guntur",
		"Nellore",
		"Kurnool",
		"Rajahmundry",
		"Tirupati",
		"Kakinada",
		"Kadapa",
		"Anantapur",
		"Vizianagaram",
		"Eluru",
		"Ongole",
		"Nandyal",
		"Machilipatnam",
		"Chittoor",
		"Srikakulam",
		"Proddatur",
		"Tenali",
		"Adoni",
	],
	ARUNACHAL_PRADESH: [
		"Itanagar",
		"Naharlagun",
		"Pasighat",
		"Tawang",
		"Ziro",
		"Bomdila",
		"Tezu",
		"Along",
		"Changlang",
		"Roing",
	],
	ASSAM: [
		"Guwahati",
		"Silchar",
		"Dibrugarh",
		"Jorhat",
		"Nagaon",
		"Tinsukia",
		"Tezpur",
		"Bongaigaon",
		"Karimganj",
		"Sivasagar",
		"Goalpara",
		"Barpeta",
		"North Lakhimpur",
		"Diphu",
		"Dhubri",
		"Golaghat",
		"Hailakandi",
		"Nalbari",
	],
	BIHAR: [
		"Patna",
		"Gaya",
		"Bhagalpur",
		"Muzaffarpur",
		"Purnia",
		"Darbhanga",
		"Bihar Sharif",
		"Arrah",
		"Begusarai",
		"Katihar",
		"Munger",
		"Chapra",
		"Saharsa",
		"Sasaram",
		"Hajipur",
		"Siwan",
		"Motihari",
		"Bettiah",
		"Samastipur",
		"Danapur",
		"Aurangabad",
	],
	CHHATTISGARH: [
		"Raipur",
		"Bhilai",
		"Bilaspur",
		"Korba",
		"Durg",
		"Rajnandgaon",
		"Jagdalpur",
		"Raigarh",
		"Ambikapur",
		"Dhamtari",
		"Mahasamund",
		"Chirmiri",
		"Kanker",
		"Kawardha",
	],
	GOA: [
		"Panaji",
		"Margao",
		"Vasco da Gama",
		"Mapusa",
		"Ponda",
		"Bicholim",
		"Curchorem",
		"Cuncolim",
		"Canacona",
		"Valpoi",
	],
	GUJARAT: [
		"Ahmedabad",
		"Surat",
		"Vadodara",
		"Rajkot",
		"Bhavnagar",
		"Jamnagar",
		"Junagadh",
		"Gandhinagar",
		"Anand",
		"Nadiad",
		"Morbi",
		"Mehsana",
		"Bharuch",
		"Vapi",
		"Navsari",
		"Porbandar",
		"Godhra",
		"Patan",
		"Palanpur",
		"Valsad",
		"Surendranagar",
		"Gandhidham",
	],
	HARYANA: [
		"Faridabad",
		"Gurugram",
		"Panipat",
		"Ambala",
		"Yamunanagar",
		"Rohtak",
		"Hisar",
		"Karnal",
		"Sonipat",
		"Panchkula",
		"Bhiwani",
		"Sirsa",
		"Bahadurgarh",
		"Jind",
		"Kaithal",
		"Rewari",
		"Kurukshetra",
		"Palwal",
	],
	HIMACHAL_PRADESH: [
		"Shimla",
		"Dharamshala",
		"Solan",
		"Mandi",
		"Kullu",
		"Manali",
		"Bilaspur",
		"Una",
		"Hamirpur",
		"Chamba",
		"Nahan",
		"Palampur",
		"Kasauli",
	],
	JHARKHAND: [
		"Ranchi",
		"Jamshedpur",
		"Dhanbad",
		"Bokaro Steel City",
		"Deoghar",
		"Hazaribagh",
		"Giridih",
		"Ramgarh",
		"Medininagar",
		"Chaibasa",
		"Dumka",
		"Phusro",
		"Gumla",
	],
	KARNATAKA: [
		"Bengaluru",
		"Mysuru",
		"Hubballi",
		"Mangaluru",
		"Belagavi",
		"Kalaburagi",
		"Davanagere",
		"Ballari",
		"Vijayapura",
		"Shivamogga",
		"Tumakuru",
		"Raichur",
		"Bidar",
		"Hospet",
		"Hassan",
		"Udupi",
		"Chikkamagaluru",
		"Bagalkot",
		"Chitradurga",
		"Kolar",
		"Mandya",
		"Gadag",
	],
	KERALA: [
		"Thiruvananthapuram",
		"Kochi",
		"Kozhikode",
		"Thrissur",
		"Kollam",
		"Kannur",
		"Alappuzha",
		"Palakkad",
		"Malappuram",
		"Kottayam",
		"Pathanamthitta",
		"Idukki",
		"Kasaragod",
		"Wayanad",
		"Ernakulam",
	],
	MADHYA_PRADESH: [
		"Bhopal",
		"Indore",
		"Jabalpur",
		"Gwalior",
		"Ujjain",
		"Sagar",
		"Dewas",
		"Satna",
		"Ratlam",
		"Rewa",
		"Katni",
		"Singrauli",
		"Burhanpur",
		"Khandwa",
		"Bhind",
		"Chhindwara",
		"Guna",
		"Shivpuri",
		"Vidisha",
		"Damoh",
		"Mandsaur",
	],
	MAHARASHTRA: [
		"Mumbai",
		"Pune",
		"Nagpur",
		"Nashik",
		"Thane",
		"Aurangabad",
		"Solapur",
		"Kolhapur",
		"Amravati",
		"Navi Mumbai",
		"Sangli",
		"Akola",
		"Latur",
		"Dhule",
		"Ahmednagar",
		"Chandrapur",
		"Jalgaon",
		"Nanded",
		"Satara",
		"Ratnagiri",
		"Wardha",
		"Yavatmal",
	],
	MANIPUR: [
		"Imphal",
		"Thoubal",
		"Bishnupur",
		"Churachandpur",
		"Ukhrul",
		"Senapati",
		"Kakching",
		"Jiribam",
		"Tamenglong",
		"Moreh",
	],
	MEGHALAYA: [
		"Shillong",
		"Tura",
		"Jowai",
		"Nongstoin",
		"Baghmara",
		"Williamnagar",
		"Resubelpara",
		"Mairang",
	],
	MIZORAM: [
		"Aizawl",
		"Lunglei",
		"Champhai",
		"Serchhip",
		"Kolasib",
		"Saiha",
		"Lawngtlai",
		"Mamit",
	],
	NAGALAND: [
		"Kohima",
		"Dimapur",
		"Mokokchung",
		"Tuensang",
		"Wokha",
		"Zunheboto",
		"Phek",
		"Mon",
	],
	ODISHA: [
		"Bhubaneswar",
		"Cuttack",
		"Rourkela",
		"Berhampur",
		"Sambalpur",
		"Puri",
		"Balasore",
		"Bhadrak",
		"Baripada",
		"Jharsuguda",
		"Angul",
		"Jeypore",
		"Balangir",
		"Rayagada",
		"Koraput",
	],
	PUNJAB: [
		"Ludhiana",
		"Amritsar",
		"Jalandhar",
		"Patiala",
		"Bathinda",
		"Mohali",
		"Hoshiarpur",
		"Pathankot",
		"Moga",
		"Firozpur",
		"Batala",
		"Barnala",
		"Kapurthala",
		"Sangrur",
		"Muktsar",
		"Rupnagar",
	],
	RAJASTHAN: [
		"Jaipur",
		"Jodhpur",
		"Udaipur",
		"Kota",
		"Bikaner",
		"Ajmer",
		"Bhilwara",
		"Alwar",
		"Sikar",
		"Bharatpur",
		"Pali",
		"Sri Ganganagar",
		"Kishangarh",
		"Baran",
		"Dhaulpur",
		"Tonk",
		"Beawar",
		"Hanumangarh",
		"Churu",
		"Jhunjhunu",
		"Nagaur",
		"Barmer",
		"Chittorgarh",
	],
	SIKKIM: ["Gangtok", "Namchi", "Gyalshing", "Mangan", "Rangpo", "Jorethang"],
	TAMIL_NADU: [
		"Chennai",
		"Coimbatore",
		"Madurai",
		"Tiruchirappalli",
		"Salem",
		"Tirunelveli",
		"Erode",
		"Vellore",
		"Thoothukudi",
		"Dindigul",
		"Thanjavur",
		"Kanchipuram",
		"Karur",
		"Nagercoil",
		"Cuddalore",
		"Kumbakonam",
		"Tiruppur",
		"Hosur",
		"Sivakasi",
		"Nagapattinam",
	],
	TELANGANA: [
		"Hyderabad",
		"Warangal",
		"Nizamabad",
		"Karimnagar",
		"Khammam",
		"Ramagundam",
		"Mahbubnagar",
		"Nalgonda",
		"Adilabad",
		"Suryapet",
		"Siddipet",
		"Miryalaguda",
		"Secunderabad",
	],
	TRIPURA: [
		"Agartala",
		"Udaipur",
		"Dharmanagar",
		"Kailashahar",
		"Belonia",
		"Khowai",
		"Ambassa",
		"Sonamura",
	],
	UTTAR_PRADESH: [
		"Lucknow",
		"Kanpur",
		"Agra",
		"Varanasi",
		"Meerut",
		"Prayagraj",
		"Ghaziabad",
		"Noida",
		"Bareilly",
		"Aligarh",
		"Moradabad",
		"Saharanpur",
		"Gorakhpur",
		"Ayodhya",
		"Jhansi",
		"Mathura",
		"Firozabad",
		"Muzaffarnagar",
		"Rampur",
		"Shahjahanpur",
		"Farrukhabad",
		"Sitapur",
		"Etawah",
		"Mirzapur",
		"Bulandshahr",
		"Hapur",
		"Gonda",
		"Basti",
	],
	UTTARAKHAND: [
		"Dehradun",
		"Haridwar",
		"Roorkee",
		"Haldwani",
		"Rudrapur",
		"Kashipur",
		"Rishikesh",
		"Nainital",
		"Almora",
		"Pithoragarh",
		"Kotdwar",
		"Ramnagar",
	],
	WEST_BENGAL: [
		"Kolkata",
		"Howrah",
		"Durgapur",
		"Asansol",
		"Siliguri",
		"Bardhaman",
		"Malda",
		"Kharagpur",
		"Baharampur",
		"Habra",
		"Krishnanagar",
		"Jalpaiguri",
		"Darjeeling",
		"Cooch Behar",
		"Raiganj",
		"Balurghat",
		"Purulia",
		"Bankura",
		"Midnapore",
		"Haldia",
	],
	ANDAMAN_AND_NICOBAR_ISLANDS: [
		"Port Blair",
		"Diglipur",
		"Rangat",
		"Mayabunder",
		"Car Nicobar",
	],
	CHANDIGARH: ["Chandigarh"],
	DADRA_AND_NAGAR_HAVELI_AND_DAMAN_AND_DIU: ["Daman", "Diu", "Silvassa"],
	DELHI: [
		"New Delhi",
		"Dwarka",
		"Rohini",
		"Karol Bagh",
		"Saket",
		"Janakpuri",
		"Connaught Place",
		"Pitampura",
	],
	JAMMU_AND_KASHMIR: [
		"Srinagar",
		"Jammu",
		"Anantnag",
		"Baramulla",
		"Sopore",
		"Udhampur",
		"Kathua",
		"Poonch",
		"Rajouri",
		"Kupwara",
		"Pulwama",
	],
	LADAKH: ["Leh", "Kargil"],
	LAKSHADWEEP: ["Kavaratti", "Agatti", "Minicoy", "Amini"],
	PUDUCHERRY: ["Puducherry", "Karaikal", "Mahe", "Yanam"],
};

const stateLabelByValue = new Map(STATES.map((s) => [s.value, s.label]));

export const CITY_OPTIONS: CityOption[] = Object.entries(
	STATE_CITY_MAP,
).flatMap(([stateValue, cities]) => {
	const stateLabel = stateLabelByValue.get(stateValue) ?? stateValue;
	return cities.map((city) => ({
		city,
		state: stateValue,
		value: `${stateValue}__${slugify(city)}`,
		label: `${city}, ${stateLabel}`,
	}));
});
