import { type TableUser } from "../../utils/types";
import type { Dealer } from "./pages/DealerMaster/common.types";

export const mockUsers: TableUser[] = [
	{
		id: 1,
		name: "Angelique Morse",
		email: "benny89@yahoo.com",
		phone: "+46 8 123 456",
		company: "Wuckert Inc",
		role: "Content Creator",
		status: "Blocked",
		avatar: "https://i.pravatar.cc/150?img=1",
	},
	{
		id: 2,
		name: "Ariana Lang",
		email: "avery43@hotmail.com",
		phone: "+54 11 1234-5678",
		company: "Feest Group",
		role: "IT Administrator",
		status: "Inactive",
		avatar: "https://i.pravatar.cc/150?img=2",
	},
	{
		id: 3,
		name: "Aspen Schmitt",
		email: "mireya13@hotmail.com",
		phone: "+34 91 123 4567",
		company: "Kihn, Marquardt and Crist",
		role: "Financial Planner",
		status: "Blocked",
		avatar: "https://i.pravatar.cc/150?img=3",
	},
	{
		id: 4,
		name: "Brycen Jimenez",
		email: "brayden.smith@gmail.com",
		phone: "+52 55 1234 5678",
		company: "Rempel, Hand and Herzog",
		role: "HR Recruiter",
		status: "Active",
		avatar: "https://i.pravatar.cc/150?img=4",
	},
	{
		id: 5,
		name: "Clara Rodriguez",
		email: "clara.rodriguez@gmail.com",
		phone: "+1 202 555 0123",
		company: "TechNova Solutions",
		role: "UI/UX Designer",
		status: "Active",
		avatar: "https://i.pravatar.cc/150?img=5",
	},
	{
		id: 6,
		name: "Daniel Nguyen",
		email: "daniel.nguyen@outlook.com",
		phone: "+84 28 1234 5678",
		company: "Saigon Digital",
		role: "Frontend Developer",
		status: "Inactive",
		avatar: "https://i.pravatar.cc/150?img=6",
	},
	{
		id: 7,
		name: "Emma Thompson",
		email: "emma.t@gmail.com",
		phone: "+44 20 7946 0958",
		company: "Bright Media Ltd",
		role: "Marketing Manager",
		status: "Active",
		avatar: "https://i.pravatar.cc/150?img=7",
	},
	{
		id: 8,
		name: "Felix Müller",
		email: "felix.mueller@gmx.de",
		phone: "+49 30 123456",
		company: "Berlin Tech GmbH",
		role: "DevOps Engineer",
		status: "Blocked",
		avatar: "https://i.pravatar.cc/150?img=8",
	},
	{
		id: 9,
		name: "Isabella Rossi",
		email: "isabella.rossi@gmail.com",
		phone: "+39 06 6982",
		company: "Roma Consulting",
		role: "Business Analyst",
		status: "Active",
		avatar: "https://i.pravatar.cc/150?img=9",
	},
	{
		id: 10,
		name: "James Wilson",
		email: "james.wilson@yahoo.com",
		phone: "+61 2 1234 5678",
		company: "Sydney Enterprises",
		role: "Project Manager",
		status: "Inactive",
		avatar: "https://i.pravatar.cc/150?img=10",
	},
];

export const mockDepartments = [
	{ id: 1, name: "Sales & Marketing", status: "Active" },
	{ id: 2, name: "Spare Parts", status: "Active" },
	{ id: 3, name: "Mining & Construction", status: "Inactive" },
	{ id: 4, name: "Service", status: "Active" },
	{ id: 5, name: "Others", status: "Inactive" },
];

export const dealers: Dealer[] = [
	{
		id: 1,
		dealerName: "Shree Balaji Motors",
		dealerCode: "DLR001",
		location: "Bangalore",
		state: "Karnataka",
		region: "South",
		contactPerson: "Ramesh Kumar",
		contactNumber: "+91 9876543210",
		status: "Active",
	},
	{
		id: 2,
		dealerName: "Sri Sai Earthmovers",
		dealerCode: "DLR002",
		location: "Hyderabad",
		state: "Telangana",
		region: "South",
		contactPerson: "Mahesh Reddy",
		contactNumber: "+91 9845012345",
		status: "Inactive",
	},
	{
		id: 3,
		dealerName: "Metro Heavy Equipment",
		dealerCode: "DLR003",
		location: "Mumbai",
		state: "Maharashtra",
		region: "West",
		contactPerson: "Anil Desai",
		contactNumber: "+91 9988776655",
		status: "Active",
	},
	{
		id: 4,
		dealerName: "Eastern Infra Solutions",
		dealerCode: "DLR004",
		location: "Kolkata",
		state: "West Bengal",
		region: "East",
		contactPerson: "Sourav Banerjee",
		contactNumber: "+91 9123456789",
		status: "Blocked",
	},
	{
		id: 5,
		dealerName: "Capital Machinery Co.",
		dealerCode: "DLR005",
		location: "New Delhi",
		state: "Delhi",
		region: "North",
		contactPerson: "Vikas Sharma",
		contactNumber: "+91 9898989898",
		status: "Active",
	},
	{
		id: 6,
		dealerName: "Western Tractors",
		dealerCode: "DLR006",
		location: "Ahmedabad",
		state: "Gujarat",
		region: "West",
		contactPerson: "Jignesh Patel",
		contactNumber: "+91 9000001122",
		status: "Inactive",
	},
	{
		id: 7,
		dealerName: "Southern Construction Hub",
		dealerCode: "DLR007",
		location: "Chennai",
		state: "Tamil Nadu",
		region: "South",
		contactPerson: "Arun Prakash",
		contactNumber: "+91 9555666777",
		status: "Active",
	},
	{
		id: 8,
		dealerName: "Northline Equipments",
		dealerCode: "DLR008",
		location: "Chandigarh",
		state: "Punjab",
		region: "North",
		contactPerson: "Gurpreet Singh",
		contactNumber: "+91 9788884444",
		status: "Blocked",
	},
	{
		id: 9,
		dealerName: "Coastal Infra Traders",
		dealerCode: "DLR009",
		location: "Kochi",
		state: "Kerala",
		region: "South",
		contactPerson: "Nikhil Menon",
		contactNumber: "+91 9444555666",
		status: "Active",
	},
	{
		id: 10,
		dealerName: "Central India Machinery",
		dealerCode: "DLR010",
		location: "Bhopal",
		state: "Madhya Pradesh",
		region: "Central",
		contactPerson: "Rahul Tiwari",
		contactNumber: "+91 9111222333",
		status: "Inactive",
	},
];
