import { type TableUser } from "../../utils/types";

export const mockUsers: TableUser[] = [
	{
		id: 1,
		name: "Angelique Morse",
		email: "benny89@yahoo.com",
		phone: "+46 8 123 456",
		company: "Wuckert Inc",
		role: "Content Creator",
		status: "Blocked",
		avatar: "https://i.pravatar.cc/150?img=1",
	},
	{
		id: 2,
		name: "Ariana Lang",
		email: "avery43@hotmail.com",
		phone: "+54 11 1234-5678",
		company: "Feest Group",
		role: "IT Administrator",
		status: "Inactive",
		avatar: "https://i.pravatar.cc/150?img=2",
	},
	{
		id: 3,
		name: "Aspen Schmitt",
		email: "mireya13@hotmail.com",
		phone: "+34 91 123 4567",
		company: "Kihn, Marquardt and Crist",
		role: "Financial Planner",
		status: "Blocked",
		avatar: "https://i.pravatar.cc/150?img=3",
	},
	{
		id: 4,
		name: "Brycen Jimenez",
		email: "brayden.smith@gmail.com",
		phone: "+52 55 1234 5678",
		company: "Rempel, Hand and Herzog",
		role: "HR Recruiter",
		status: "Active",
		avatar: "https://i.pravatar.cc/150?img=4",
	},
	{
		id: 5,
		name: "Clara Rodriguez",
		email: "clara.rodriguez@gmail.com",
		phone: "+1 202 555 0123",
		company: "TechNova Solutions",
		role: "UI/UX Designer",
		status: "Active",
		avatar: "https://i.pravatar.cc/150?img=5",
	},
	{
		id: 6,
		name: "Daniel Nguyen",
		email: "daniel.nguyen@outlook.com",
		phone: "+84 28 1234 5678",
		company: "Saigon Digital",
		role: "Frontend Developer",
		status: "Inactive",
		avatar: "https://i.pravatar.cc/150?img=6",
	},
	{
		id: 7,
		name: "Emma Thompson",
		email: "emma.t@gmail.com",
		phone: "+44 20 7946 0958",
		company: "Bright Media Ltd",
		role: "Marketing Manager",
		status: "Active",
		avatar: "https://i.pravatar.cc/150?img=7",
	},
	{
		id: 8,
		name: "Felix Müller",
		email: "felix.mueller@gmx.de",
		phone: "+49 30 123456",
		company: "Berlin Tech GmbH",
		role: "DevOps Engineer",
		status: "Blocked",
		avatar: "https://i.pravatar.cc/150?img=8",
	},
	{
		id: 9,
		name: "Isabella Rossi",
		email: "isabella.rossi@gmail.com",
		phone: "+39 06 6982",
		company: "Roma Consulting",
		role: "Business Analyst",
		status: "Active",
		avatar: "https://i.pravatar.cc/150?img=9",
	},
	{
		id: 10,
		name: "James Wilson",
		email: "james.wilson@yahoo.com",
		phone: "+61 2 1234 5678",
		company: "Sydney Enterprises",
		role: "Project Manager",
		status: "Inactive",
		avatar: "https://i.pravatar.cc/150?img=10",
	},
];
