import {
	ClipboardCheck,
	Database,
	FileText,
	HatGlasses,
	Hospital,
	Megaphone,
	MonitorCog,
	PackageSearch,
	ScrollText,
	UserCheck,
	Warehouse,
} from "lucide-react";

export const actions = [
	{
		icon: Megaphone,
		title: "Marketing Activity Planner",
		description: "Plan, track, and approve marketing events and campaigns.",
		path: "/marketing/activity-planner/listing",
		appKey: "MAP",
		isActive: true,
	},
	{
		icon: MonitorCog,
		title: "Administrator",
		description: "System config, user roles, and access management.",
		path: "/admin/users",
		appKey: "ADMIN",
		isActive: false,
	},
	{
		icon: FileText,
		title: "Vendor Onboarding",
		description: "Submit, review, and process dealer reimbursements.",
		path: "/vendor/onboarding/listing",
		appKey: "VENDOR_ONBOARDING",
		isActive: false,
	},
	{
		icon: UserCheck,
		title: "Workflows",
		description:
			"Manage vendor registration, verification, and approval processes.",
		path: "/workflow/listing",
		appKey: "WORKFLOW",
		isActive: false,
	},
	{
		icon: Hospital,
		title: "Medical Forms",
		description: "Configure and compare machinery specs for customer needs.",
		path: "/medi-claim/create",
		appKey: "MEDICAL_CLAIM",
		isActive: false,
	},
	{
		icon: PackageSearch,
		title: "Product Selector",
		description: "Configure and compare machinery specs for customer needs.",
		path: "/",
		appKey: "PRODUCT_SELECTOR",
		isActive: false,
	},
	{
		icon: ClipboardCheck,
		title: "Audit",
		description: "Conduct audits and compliance checks.",
		path: "/",
		appKey: "AUDIT",
		isActive: false,
	},

	{
		icon: UserCheck,
		title: "Key Account",
		description: "Manage strategic accounts and relationship data.",
		path: "/",
		appKey: "KEY_ACCOUNT",
		isActive: false,
	},
	{
		icon: Database,
		title: "Customer Master Data",
		description: "Centralised customer records, segments, and profiles.",
		path: "/",
		appKey: "CUSTOMER_MASTER_DATA",
		isActive: false,
	},

	{
		icon: Warehouse,
		title: "Asset Master",
		description: "Track and manage machinery and equipment inventory.",
		path: "/",
		appKey: "ASSET_MASTER",
		isActive: false,
	},
	{
		icon: HatGlasses,
		title: "MSI",
		description: "Market share intelligence and competitive analysis.",
		path: "/",
		appKey: "MSI",
		isActive: false,
	},
	{
		icon: ScrollText,
		title: "ASC",
		description: "After-sales and service centre operations.",
		path: "/",
		appKey: "ASC",
		isActive: false,
	},
] as const;
